# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce2e8dfa52d12b23d0d56309cd16c9289b8893fba60015639f4953d08453e2585b6a89de1265a6166f1a7f9c7f7ab88c06e3c9b8719310358783b097b7945466

test:
  secret_key_base: 8c4692953b59f19c68c699352719127db50c5b0941e8ddf88d5b934b8c16c562fc2be819c1a05d210b7f34f8af7dd148e15478392da390d066091650e001eecc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
